### PR TITLE
Mac Catalyst Support

### LINKED ISSUE #534: Using OneSignal and Catalyst
**Description:**

Hi there! I would like to use Catalyst in order to run my app on the Mac as well. Unfortunately I get an Error in my notification target regarding the OneSignal SDK.
Is it possible to use the iOS SDK with Catalyst?

> ld: in /<PROJECT_PATH>/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-x86_64-master.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '<PROJECT_PATH>/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks!

**Environment**

Xcode 11 GM Seed 1 
iOS 13
OneSignal via Cocoapods (latest version)

**Steps to Reproduce Issue:**

1. Install the latest iOS SDK using Cocoapods
2. Setup OneSignal in your NotificationExtension as shown below. 
3. Enable Mac in your Deployment Info
4. Try to run your code on your Mac using macOS 10.15

```
import UserNotifications
import OneSignal

class NotificationService: UNNotificationServiceExtension {
    
    var contentHandler: ((UNNotificationContent) -> Void)?
    var receivedRequest: UNNotificationRequest!
    var bestAttemptContent: UNMutableNotificationContent?
    
    override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
        self.receivedRequest = request;
        self.contentHandler = contentHandler
        bestAttemptContent = (request.content.mutableCopy() as? UNMutableNotificationContent)
        
        if let bestAttemptContent = bestAttemptContent {
            OneSignal.didReceiveNotificationExtensionRequest(self.receivedRequest, with: self.bestAttemptContent)
            contentHandler(bestAttemptContent)
        }
    }
    
    override func serviceExtensionTimeWillExpire() {
        // Called just before the extension will be terminated by the system.
        // Use this as an opportunity to deliver your "best attempt" at modified content, otherwise the original push payload will be used.
        if let contentHandler = contentHandler, let bestAttemptContent =  bestAttemptContent {
            OneSignal.serviceExtensionTimeWillExpireRequest(self.receivedRequest, with: self.bestAttemptContent)
            contentHandler(bestAttemptContent)
        }
    }
    
}
```

### PR DESCRIPTION
**Pull request by rgomezp**
### Dev App
- Added additional architectures to support Mac Catalyst (x86_64h)

### OneSignal.m
- Since Mac Catalyst and Simulator both have x86_64 for the `deviceModel`, we need a way to differentiate between the two in the dashboard
   - Use UIDevice `systemName` and `deviceModel` to differentiate between Simulator and Mac Catalyst

### OneSignalHelper.m
- Abstracted device variant logic into own function `getDeviceVariant` (Simulator \<Device\>, Mac, or \<Device\>\<Version\>
- Created function `getSystemInfoMachine` to return machine info like @"x86_64" or @"iPhone9,3"

### Provisioning
- Changed `getMobileProvision` to `getProvision` since it is no longer limited to mobile (includes Catalyst)

### Testing
- Created `UIDeviceOverrider` to use test mocks:
   - `model` (e.g: "iPhone", "iPad")
   - `systemName` (e.g: "iOS", "Mac OS X")

### Fat Framework Script
- Need a way to build a fat framework that supports both iOS, Simulator, and Catalyst:
   - Use `xcodebuild` (specifically from Xcode 10.1) for `iphoneos` && `iphonesimulator`
   - Use `xcodebuild` (specifically from Xcode 11) for Mac Catalyst
- SYMROOT creates a folder called `temp` where the fat framework is built before being copied to its final destination (instead of building it inside of Derived Data)
- Mach-O type is set to static

Closes #534

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/560)

### CODE REVIEW

File: iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m [hunk 1]
```diff
@@ -162,11 +162,14 @@ - (void)testBasicInitTest {
     
     NSLog(@"CHECKING LAST HTTP REQUEST");
     
+    NSString *model = [[UIDevice currentDevice] model];
+    NSString *deviceModel = [@"Simulator " stringByAppendingString:model];
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m]: Let's add a comment here of what the final value should be for the iOS simulator. It should be "Simulator iOS" correct?

File: iOS_SDK/OneSignalSDK/build_fat_framework.sh [hunk 2]
```diff
@@ -1,52 +1,45 @@
...
+WORKING_DIR=$(pwd)
+
+# For backwards compatible bitcode we need to build iphonesimulator + iphoneos with 3 versions behind the latest.
+#       However variant=Mac Catalyst needs to be be Xcode 11.0
+/Applications/Xcode10.1.app/Contents/Developer/usr/bin/xcodebuild -configuration "Debug" MACH_O_TYPE="staticlib" -sdk "iphonesimulator" ARCHS="x86_64" -project "OneSignal.xcodeproj" -scheme "OneSignalFramework" SYMROOT="temp/"
+/Applications/Xcode10.1.app/Contents/Developer/usr/bin/xcodebuild -configuration "Debug" MACH_O_TYPE="staticlib" -sdk "iphoneos" ARCHS="armv7 armv7s arm64 arm64e i386"  -project "OneSignal.xcodeproj" -scheme "OneSignalFramework" SYMROOT="temp/"
+xcodebuild -configuration "Debug" ARCHS="x86_64h" -destination 'platform=macOS,variant=Mac Catalyst' MACH_O_TYPE="staticlib" -project "OneSignal.xcodeproj" -scheme "OneSignalFramework" SYMROOT="temp/"
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/build_fat_framework.sh]: Same as above however call it `XCODEBUILD_11_0`. We can also make a comment once Apple drops support for Xcode 10 we can remove `XCODEBUILD_11_0` and use `XCODEBUILD_OLDEST_SUPPORTED` for all 3 build commands.

File: iOS_SDK/OneSignalSDK/build_fat_framework.sh [hunk 3]
```diff
@@ -1,52 +1,45 @@
...
 set -e
-set -o pipefail
 
-# Build x86 based framework to support iOS simulator 
-xcodebuild -configuration "${CONFIGURATION}" -project "${PROJECT_NAME}.xcodeproj" -target ${ONESIGNAL_TARGET_NAME} -sdk "iphonesimulator${SDK_VERSION}" "${ACTION}" ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode RUN_CLANG_STATIC_ANALYZER=NO CLANG_ENABLE_MODULE_DEBUGGING=NO BUILD_DIR="${BUILD_DIR}" BUILD_ROOT="${BUILD_ROOT}" SYMROOT="${SYMROOT}" MACH_O_TYPE=${ONESIGNAL_MACH_O_TYPE} -UseModernBuildSystem=NO
+WORKING_DIR=$(pwd)
+
+# For backwards compatible bitcode we need to build iphonesimulator + iphoneos with 3 versions behind the latest.
+#       However variant=Mac Catalyst needs to be be Xcode 11.0
+/Applications/Xcode10.1.app/Contents/Developer/usr/bin/xcodebuild -configuration "Debug" MACH_O_TYPE="staticlib" -sdk "iphonesimulator" ARCHS="x86_64" -project "OneSignal.xcodeproj" -scheme "OneSignalFramework" SYMROOT="temp/"
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/build_fat_framework.sh]: Let's define `/Applications/Xcode10.1.app/Contents/Developer/usr/bin/xcodebuild` as a variable so it isn't repeated twice. Call it something like `XCODEBUILD_OLDEST_SUPPORTED`

File: iOS_SDK/OneSignalSDK/build_fat_framework.sh [hunk 4]
```diff
@@ -72,5 +65,9 @@ cd Versions
 ln -s A Current
 
 # Copy the built product to the final destination in {repo}/iOS_SDK/OneSignalSDK/Framework
-rm -rf "${ONESIGNAL_DESTINATION_PATH}/${ONESIGNAL_OUTPUT_NAME}.framework"
-cp -a "${FINAL_FRAMEWORK_LOCATION}" "${ONESIGNAL_DESTINATION_PATH}/${ONESIGNAL_OUTPUT_NAME}.framework"
\ No newline at end of file
+rm -rf "${WORKING_DIR}/Framework/OneSignal.framework"
+cp -a "${FINAL_FRAMEWORK}" "${WORKING_DIR}/Framework/OneSignal.framework"
+
+open ${WORKING_DIR}/Framework
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/build_fat_framework.sh]: Let's print something to the console we so know what this open is showing us. Maybe something like `echo "Opening final release framework in Finder:${WORKING_DIR}/Framework/OneSignal.framework"`

File: iOS_SDK/OneSignalSDK/build_fat_framework.sh [hunk 5]
```diff
@@ -1,52 +1,45 @@
...
+WORKING_DIR=$(pwd)
+
+# For backwards compatible bitcode we need to build iphonesimulator + iphoneos with 3 versions behind the latest.
+#       However variant=Mac Catalyst needs to be be Xcode 11.0
+/Applications/Xcode10.1.app/Contents/Developer/usr/bin/xcodebuild -configuration "Debug" MACH_O_TYPE="staticlib" -sdk "iphonesimulator" ARCHS="x86_64" -project "OneSignal.xcodeproj" -scheme "OneSignalFramework" SYMROOT="temp/"
+/Applications/Xcode10.1.app/Contents/Developer/usr/bin/xcodebuild -configuration "Debug" MACH_O_TYPE="staticlib" -sdk "iphoneos" ARCHS="armv7 armv7s arm64 arm64e i386"  -project "OneSignal.xcodeproj" -scheme "OneSignalFramework" SYMROOT="temp/"
+xcodebuild -configuration "Debug" ARCHS="x86_64h" -destination 'platform=macOS,variant=Mac Catalyst' MACH_O_TYPE="staticlib" -project "OneSignal.xcodeproj" -scheme "OneSignalFramework" SYMROOT="temp/"
+
+USER=$(id -un)
+DERIVED_DATA_ONESIGNAL_DIR="${WORKING_DIR}/temp"
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/build_fat_framework.sh]: Let's make `temp` here a variable and use it in the 3 `xcodebuild` commands above. Name suggestion, `DERIVED_DATA_RELITIVE_DIR`

File: iOS_SDK/OneSignalSDK/build_fat_framework.sh (hunk 3 above)
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/build_fat_framework.sh]: Would be nice to dedup variables between these 3 `xcodebuild` commands. I see `"OneSignal.xcodeproj"` `OneSignalFramework"  and `"staticlib"` are all the same between them. Also `temp/` noted a few comments below

File: iOS_SDK/OneSignalSDK/Source/OneSignal.m [hunk 6]
```diff
@@ -1481,9 +1481,20 @@ + (void)registerUserInternal {
     
     struct utsname systemInfo;
     uname(&systemInfo);
-    let deviceModel = [NSString stringWithCString:systemInfo.machine
+    NSString *deviceModel = [NSString stringWithCString:systemInfo.machine
```
[the remark this answers is not in the document]
Comment (rgomezp) [reply iOS_SDK/OneSignalSDK/Source/OneSignal.m]: can't keep let since it would not allow reassignment

File: iOS_SDK/OneSignalSDK/OneSignal.xcodeproj/project.pbxproj [hunk 7]
```diff
@@ -1455,7 +1479,7 @@
 			isa = XCBuildConfiguration;
 			buildSettings = {
 				CLANG_ANALYZER_NONNULL = YES;
-				CLANG_ENABLE_MODULES = YES;
+				CLANG_ENABLE_MODULES = NO;
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/OneSignal.xcodeproj/project.pbxproj]: Keep this as `YES` as it might be needed for Swift projects that consume the OneSignal SDK. `CLANG_ENABLE_MODULES`

File: iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m [hunk 8]
```diff
@@ -467,6 +468,34 @@ + (BOOL)isIOSVersionLessThan:(NSString *)version {
...
+    return [NSString stringWithCString:systemInfo.machine
+                                         encoding:NSUTF8StringEncoding];
+}
+
+// This will get real device model if it is a real iOS device (Example iPhone8,2)
+// If an iOS Simulator it will return "Simulator iPhone" or "Simulator iPad"
+// If a macOS Catalyst app, return "Mac"
++ (NSString*)getDeviceVariant {
+    let systemInfoMachine = [self getSystemInfoMachine];
+    let systemName = UIDevice.currentDevice.systemName;
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m]: nit, move inside of the first if

File: iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m [hunk 9]
```diff
@@ -98,6 +99,45 @@ -(void)tearDown {
...
+    OneSignalHelperOverrider.mockIOSVersion = 10;
+    [OSMessagingController removeInstance];
+    let sharedInstance = OSMessagingController.sharedInstance;
+    XCTAssertEqualObjects(sharedInstance.class, OSMessagingController.class);
+}
+
+-(void)testSimulatorIpad {
+    OneSignalHelperOverrider.mockIOSVersion = 10;
+    [OSMessagingController removeInstance];
+    [OneSignalHelperOverrider setSystemInfoMachine:@"iPad9,3"];
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m]: Remove `setSystemInfoMachine`
`UIDevice.currentDevice.model` should be `iPad`

File: iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m [hunk 10]
```diff
@@ -98,6 +99,45 @@ -(void)tearDown {
...
+    let sharedInstance = OSMessagingController.sharedInstance;
+    XCTAssertEqualObjects(sharedInstance.class, OSMessagingController.class);
+}
+
+-(void)testOldUnsupportedIosDevice {
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m]: `testOldUnsupportedIosDevice` should be `testOldUnsupportedIphoneSimulator`

File: iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m [hunk 11]
```diff
@@ -98,6 +99,45 @@ -(void)tearDown {
...
+    [OneSignalHelperOverrider setSystemInfoMachine:@"x86_64"];
+    [UIDeviceOverrider setSystemName:@"Mac OS X"]; // e.g. @"Mac OS X" @"iOS"
+    let sharedInstance = OSMessagingController.sharedInstance;
+    XCTAssertEqualObjects(sharedInstance.class, DummyOSMessagingController.class); // sharedInstance should be dummy controller
+}
+
+-(void)testOldUnsupportedSimulatorIpad {
+    OneSignalHelperOverrider.mockIOSVersion = 8;
+    [OSMessagingController removeInstance];
+    [OneSignalHelperOverrider setSystemInfoMachine:@"iPad9,3"];
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m]: Remove `setSystemInfoMachine`
UIDevice.currentDevice.model should be iPad

File: iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m [hunk 12]
```diff
@@ -98,6 +99,45 @@ -(void)tearDown {
...
+    let sharedInstance = OSMessagingController.sharedInstance;
+    XCTAssertEqualObjects(sharedInstance.class, DummyOSMessagingController.class); // sharedInstance should be dummy controller
+}
+
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m]: Add tests for real devices

File: iOS_SDK/OneSignalSDK/build_fat_framework.sh [hunk 13]
```diff
@@ -1,52 +1,54 @@
...
+WORKING_DIR=$(pwd)
+DERIVED_DATA_RELATIVE_DIR=temp
+BUILD_CONFIG="Debug"
+BUILD_TYPE="staticlib"
+BUILD_SCHEME="OneSignalFramework"
+BUILD_PROJECT="OneSignal.xcodeproj"
+
+# NOTE: Once Apple drops support for Xcode 10, we can edit this to use same xcodebuild version for all three build commands
+XCODEBUILD_OLDEST_SUPPORTED=/Applications/Xcode10.1.app/Contents/Developer/usr/bin/xcodebuild
+XCODEBUILD_11_0=xcodebuild
```
Comment (jkasten2) [inline iOS_SDK/OneSignalSDK/build_fat_framework.sh]: Should be hard coded to `Xcode11.0.app` like above for 10.1

**Comment by sabiland** [comment]
I have tried today with latest OneSignal (pod), and I still get error when building for mac catalyst:

`ld: in /Users/sabiland/Library/Mobile Documents/com~apple~CloudDocs/SabilandICloudGIT/Texturing/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-x86_64-master.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '/Users/sabiland/Library/Mobile Documents/com~apple~CloudDocs/SabilandICloudGIT/Texturing/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'`

**Comment by rgomezp** [comment]
@sabiland ,
That version doesn't support Catalyst yet. We have not released the new version yet, simply merged into master. 

If you would like to build the binary yourself, feel free to give it a shot. You will need Xcode versions 11.0 and 10.1 and name them Xcode11.0.app and Xcode10.1.app. Then run the build script `build_fat_framework.sh`. This will create a new framework which you can then add to your project. Enjoy!

**Comment by sabiland** [comment]
Thx for info @rgomezp, I'll wait for OneSignal release.
