### PR TITLE
Calling the failure block of send tags for bad input

### LINKED ISSUE #951: sendTags doesn't return error when tag type is invalid
**Description:**
`OneSignal.sendTags` callback doesn't ever complete when sending invalid tag (e.g. a date value)

**Environment**
iOS SDK version 3.5.2
via Cocoapods

**Steps to Reproduce Issue:**
```
var tags:[String:Any] = [
      "numPosts": user.numPosts,
      "rating": user.rating
  ]
  if let date = user.signupDate as? Date{
      tags["signup"] = date
  }
  
  OneSignal.sendTags(tags, onSuccess: {
      _ in
      //never gets here and tags are not sent
      print("one sig success")
  }, onFailure: {
      failure in
      //never gets here
      print("sendTags failure \(failure?.localizedDescription ?? "")")
  })
```

### PR DESCRIPTION
**Pull request by emawby**
Previously we would log a warning and return on bad input for the sendTags method. Now we will also call the failure block with an error object with information on what went wrong. This fixes #951

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/952)

### CODE REVIEW

File: iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m [hunk 1]
```diff
@@ -1388,15 +1388,24 @@ - (void)testSendBadObjectInTags {
...
+        XCTAssertEqualObjects(error.domain, @"com.onesignal.tags");
+        [errorExpectation fulfill];
+    }];
     
     // Make sure the tags were not sent.
     [NSObjectOverrider runPendingSelectors];
     [UnitTestCommonMethods runBackgroundThreads];
     [NSObjectOverrider runPendingSelectors];
     
+
```
Comment (Jeasmine) [inline iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m:1406]: Can we remove this extra \n?

**Review by Jeasmine — APPROVED** [review]
LGTM nit comment

File: iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m (hunk 1 above)
Comment (emawby) [reply iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m]: done!

**Review by jkasten2 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/952)* status: all files reviewed, 1 unresolved discussion (waiting on @Jeasmine)
